

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const LOGIN = 'LOGIN';
export const CONT_AS_GUEST = 'CONT_AS_GUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'


export const REPORT_INCIDENT_LOCATION_FLOOR_DATA = 'REPORT_INCIDENT_LOCATION_FLOOR_DATA'

export const REPORT_INCIDENT_ALL_DATA = 'REPORT_INCIDENT_ALL_DATA'

